### ISSUE TITLE
Teach user how to toggle torah/chumash side using keyboard

### ISSUE THREAD

**Issue by akivajgordon** [akivajgordon/tikkun.io#1]
Currently, holding down the <kbd>.</kbd> (i.e. period) character can be used to quickly toggle the torah side vs. chumash side, but it is not discoverable. There should be some method of teaching the user about this trick.

**Comment by JackYoungblood** [comment]
This is a perfect feature while studying... When I start studying  I can show the t'amim and nekudot and then press the period to test myself on the torah script. As I know the reading better I can show the torah script and press the period if/when I need to cheat.

One suggestion I would make is that you move this functionality to the space bar as it's so much more accessible than having to hunt down a small keyboard key.

Thanks for bringing this functionality to my attention.

**Comment by akivajgordon** [comment]
Since v1.0, it's actually now the <kbd>Shift</kbd> key that is used for the toggle.

**Comment by akivajgordon** [comment]
Closed with PR #28
