### ISSUE TITLE
Accommodation for double parshiot

### ISSUE THREAD

**Issue by JackYoungblood** [akivajgordon/tikkun.io#10]
I'd like to see navigation in the pasha listings for double parshiot. When clicking on those links the aliyah breaks should show the aliyah breaks for the double parsha assignment.

edit - Never mind the comment above. I see that you now have the double parsha aliyah break indicators showing when I look at the individual parshiot. Kol Hakavod. I'll leave this RFE in place so you can see that someone had this thought but don't spend any time on it as the current functionality suffices just fine

**Comment by akivajgordon** [comment]
Closing because, as you mentioned in your edit, this functionality already exists:

![double-parsha-aliyot](https://cloud.githubusercontent.com/assets/6025036/23342467/bc9ac71a-fc28-11e6-857a-02266bf1778b.png)
