### ISSUE TITLE
Add Rosh Chodesh to parsha picker

### ISSUE THREAD

**Issue by DovPer** [akivajgordon/tikkun.io#109]
I really love and use this resource. 
Can there be a shortcut added to the Rosh Chodesh reading in the Chagim section?
Thanks!

**Comment by akivajgordon** [comment]
Yes, thanks for reporting! Not sure how I overlooked that... I actually thought it was already there.

**Comment by akivajgordon** [comment]
@DovPer – Deployed!

<img width="520" alt="rosh-chodesh" src="https://user-images.githubusercontent.com/6025036/202088002-2e1dfad1-ecff-4561-8ab5-19b3b0f1f11d.png">
