### ISSUE TITLE
Yitro Ta'am Elyon

### ISSUE THREAD

**Issue by BinyaminFarnoosh** [akivajgordon/tikkun.io#111]
Is there a way to to get Ta'am elyon on the 10 Dibrot in Yitro.
Seems to be some regular and elyon mixed

**Comment by akivajgordon** [comment]
@BinyaminFarnoosh Thanks for raising this! This is a duplicate of #63 , but thanks for reminding me. I probably won't have time this week, but hopefully I can resolve it before ואתחנן rolls around. So sorry about that.

**Comment by BinyaminFarnoosh** [comment]
Thanks for explaining.
Kol tuv
