### ISSUE TITLE
no toggling on mac?

### ISSUE THREAD

**Issue by jeremy-rutman** [akivajgordon/tikkun.io#114]
I can't seem to toggle vowels/cantillations (which apparently is supposed to happen upon pressing the period '.') This is for firefox and chrome on mac M1 running ventura 13

**Comment by akivajgordon** [comment]
@jeremy-rutman Use the "Shift" key instead, as shown in the tooltip (hover over the toggle) in the screenshot below:

![Screenshot 2023-09-22 at 4 40 28 PM](https://github.com/akivajgordon/tikkun.io/assets/6025036/ee6a4930-f795-4d50-99c6-5f7333d662f6)

It _used_ to be the period character, but I changed that several years ago. I wonder how you found that!

Thanks for using tikkun.io and for raising the flag. Hope this helps!
