### ISSUE TITLE
Development Environment

### ISSUE THREAD

**Issue by SLaks** [akivajgordon/tikkun.io#121]
I finally have time to work on this, and I'm setting up local development.

 - What formatter and settings are you using, so I can configure VS Code or editorconfig to match?
 - Is there a reason that unit tests are in JS rather than TS? Do you mind if I send a PR to convert them all to TS to get type checking? (I'm not sure whether I will do this)
 - What version of Node.js are you using? (see #120)
 - Do you mind if I switch the build and dev server to use https://vitejs.dev? It's faster, and adds nice features like live reload.

**Comment by akivajgordon** [comment]
Thanks for the issue!

These days, I'm into prettier with the following config (.prettierrc):

```
{
  "semi": false,
  "singleQuote": true
}
```

and a .prettierignore:

```
dist
node_modules
```

Would love if you could add those to the project.

Unit tests are in JS for no reason other than that I started the project before TS was prominent. I converted the source to TS several months ago, but I overlooked the tests. Feel free to tackle that if you'd like.

Bumping to Node 20+ is fine by me.

Switching to Vite sounds like a good idea too. I've been using Vite on any new client project I start, so I'm familiar with it and it sounds like a reasonable idea here.

Thanks for all this!

**Comment by SLaks** [comment]
WDYT about using https://lit.dev/ for new UI components? (Eg, rewritten Parsha picker)

It's a very lightweight framework, but I find it quite helpful for rerendering UI

**Comment by akivajgordon** [comment]
I appreciate the idea.

I think the app has now outgrown these odd string-interpolated components that I made, which was basically inspired by lit but without the dependency (fun fact: this app started as a lit project, and I undid it at some point), but I'm pretty sure I want to go the React route instead.

If you're set on lit and it's lightweight in terms of knowledge/tooling/complexity, etc, I'm willing to accept it for now, but just keep in mind that I'm more likely to convert the entire project to React in the near future, including the work that you do for this. If we do it right, hopefully it won't be a ton of work.

The point is, I'd rather you make the contribution if lit is the best move for you than for you to not make the contribution at all. I'll trust your judgement for now.

**Comment by SLaks** [comment]
I've never really worked with React, but I'm not opposed to it.

I'll probably try React when I'm ready to start doing serious UI work.
