### ISSUE TITLE
Switch on click

### ISSUE THREAD

**Issue by AriMKatz** [akivajgordon/tikkun.io#139]
Hey this is cool! Would be awesome if you could switch modes with a left click anywhere on the text as well

**Comment by akivajgordon** [comment]
@AriMKatz Thanks for the suggestion!

I'm not opposed to it necessarily, but I'm exploring anything option for the left click, namely highlighting (#70), so I'm going to hold off on this suggestion for now.

Still, I hear your feedback loud and clear, and I appreciate you being part of the tikkun.io community!
