### ISSUE TITLE
Add mobile support

### ISSUE THREAD

**Issue by akivajgordon** [akivajgordon/tikkun.io#3]
On small screens (i.e. mobile devices), the lines are broken up poorly, and it's not possible to quickly jump to a specific parsha. Also, scrolling is awkward. Overall, it's a poor experience.

**Comment by JackYoungblood** [comment]
I don't think you're far from having a decent mobile experience. If I hold my phone in landscape mode the lines break correctly (I believe). Yes, there's a lot of scrolling needed but that's just a fact of life on a small phone screen. 

The only true shortcoming is the lack of navigational controls which makes the app unusable in its current state. Add a method to navigate effectively on mobile and I think I could use this while commuting on the train!

**Comment by akivajgordon** [comment]
@nizdobs Yes, the navigation on mobile is definitely the biggest issue and needs to be solved in order for it to be usable. I definitely have this one on my radar. Thanks again for the feedback!

**Comment by akivajgordon** [comment]
Resolved with PR #23 

It's not perfect by any measure, but it's definitely usable now.
