### ISSUE TITLE
Incorrect טעמי מקרא

### ISSUE THREAD

**Issue by akivajgordon** [akivajgordon/tikkun.io#33]
I've noticed a bunch of incorrect טאמי מקרא along the way, but I haven't marked them down. Let's try to keep a running list over here:

* [ ] Shoftim (בראשית יח:יד)

The partial challenge here is that the text is generated from another source, so I'd rather ask that source to update it rather than edit our own copy.

*keywords for searching: trope, ta'amei mikrah, cantillation*

**Comment by ezrag26** [comment]
Vayeilech (וילך לא:ה)
![Screen Shot 2021-09-01 at 22 29 07](https://user-images.githubusercontent.com/36003744/131733387-d00f0cc0-cf2d-42e0-8e13-6220786bbf22.png)

**Comment by akivajgordon** [comment]
Fixed with #102
