### ISSUE TITLE
Chapter numbers are missing when a new chapter starts

### ISSUE THREAD

**Issue by akivajgordon** [akivajgordon/tikkun.io#4]
I can tell when a new chapter starts because the verse indicator shows "א", but it doesn't say which chapter it is.

One possible solution is to show it like this, "יז:א" indicating 17:1 (i.e. chapter 17, verse 1).

**Comment by nizdobs** [comment]
I just happened across this today as I was using the site to prepare for Vayakhel-Pekudei. The site doesn't break out aliyot for double parshiot (which should be its own RFE) so to work around it I went to hebcal to look for the perek and pasuk of the aliyah I'm interested in. But looking at the app there's no way to know which perek you're looking at

**Comment by akivajgordon** [comment]
Fixed with commit 353d4da84f3120007d6f1ee21784052868736254
