### ISSUE TITLE
Link to tikkun.io in Hebcal

### ISSUE THREAD

**Issue by JackYoungblood** [akivajgordon/tikkun.io#93]
Akiva, this isn't an issue but I wanted to bring this to your attention. Have you seen this? https://hebcal.userecho.com/en/communities/1/topics/200-torah-reading-aliyot-link-to-a-tikkun?redirect_to_reply=1083#comment-1083

Hebcal and tikkun.io are my two favorite online torah reading sites so I'm glad to see hebcal's torah reading calendar link to tikkun.io

**Comment by akivajgordon** [comment]
@JackYoungblood – yes, it started with the issue I created on the hebcal side:

https://github.com/hebcal/dotcom/issues/42

He implemented the whole thing in a few hours I think, which was really impressive.

Thanks for your continued support, and I'm glad you've found tikkun.io useful!
