### ISSUE TITLE
Is there a way to not print with and without vowels/trope

### ISSUE THREAD

**Issue by BonEllen** [akivajgordon/tikkun.io#94]
Hi. I'd like to print a reading from Tikkun.io without vowels/trope but regardless of which view I see on the screen, it prints both view together. Can the printout match what is seen on the screen? Thank you. Attached is a .pdf version of what the printout looks like. 

[bereshit.pdf](https://github.com/akivajgordon/tikkun.io/files/7238009/bereshit.pdf)

Also, would it be possible to keep the nice, large bold text as seen on the screen? The printed version is much smaller.

**Comment by akivajgordon** [comment]
@BonEllen – sorry, I haven't been able to add proper printing support yet. I think it will be pretty challenging from where everything is right now.

That being said, I'd love to know a little bit more about your use case for why you'd like to print it. Also, I'd love to know what you'd like to see the end result looking like. Starting with a paper tikkun as a baseline, would you like to see something different than that?

Finally, I'll close this issue to consolidate with https://github.com/akivajgordon/tikkun.io/issues/69. Feel free to leave your additional feedback here or on that linked issue.
