### ISSUE TITLE
[Feature Request] Use Shlomo Stam font instead of Shlomo semiStam when cantillation marks are hidden

### ISSUE THREAD

**Issue by lord-ne** [akivajgordon/tikkun.io#96]
The Shlomo Stam font is made to look like handwritten letters in the Torah. The Shlomo semiStam font currently used is a modified version with some of the letter decorations removed or shortened to make it work with _nikkudot_ and _trop_ markings. When cantillation marks are hidden, there is no need to use Shlomo semiStam, so it would look nicer to switch to the Shlomo Stam font with the full decorations.

[Source](https://sites.google.com/site/orlaeinayim/introduction-to-fonts-with-hebrew-cantillation-marks#2):

> Several letters of the Shlomo Stam font have tags above their heads. Several letters have stings above or below their heads. The Shlomo Stam font is therefore, essentially, not intended to be used with Cantillation Marks or vowels signs - as the tags and stings may obscure them. They are intended to be used, in what is called Tikoon Korim.
> 
> The shlomo semiStam font has similar glyphs like those of the Shlomo Stam font. But the tags were removed, the stings were shortened and some glyphs were modified - so cantillation marks can be used. To review all those remarks see the followings (from Exodus 20:4):
>
>![image](https://user-images.githubusercontent.com/34069872/137610211-96979826-b203-4057-add7-4d0e755c91ac.png)

**Comment by akivajgordon** [comment]
@lord-ne I think it's a great suggestion. My initial thought with it was to keep things clean for a computer screen which is already harder on the eyes, plus that when you toggle the nikkud and trop back and forth, the distinctions are less clear when the crowns also are appearing/disappearing. 

That being said, I recognize the value of having the Torah side appear as naturally as it would appear in the Sefer Torah, so if you'd like to make a pull request, I'd be happy to give it a review to see if my thought was just a bad theory and that it really is better in practice.

**Comment by lord-ne** [comment]
Sounds good. I won't have time to make a PR for a couple weeks at least (I don't have much experience with JavaScript so it'll take me a couple hours to figure out how to do it, which I unfortunately don't have time for right now), so if anyone else wants to do it in the meantime feel free.

**Comment by akivajgordon** [comment]
@lord-ne No problem. I actually don't think it's too tricky, so I'll give it a stab tonight. And if it does turn out to be tricky, then I'll throw a comment as to why.

**Comment by akivajgordon** [comment]
@lord-ne So I just tried this out:

![2021-10-17 21 39 09](https://user-images.githubusercontent.com/6025036/137656395-a6ad4e41-3910-4085-9092-3ff5a84f58d2.gif)

I find the resulting appearance to be very underwhelming (the crowns don't appear as large as in a sefer Torah, so much so that I can't even tell how many crowns are on each letter at any reasonable font size); therefore, I don't think it's really worth the added page weight for the additional font, nor the development maintenance cost, nor the distraction for the user who is toggling back-and-forth.

I really appreciate the suggestion, and it was definitely worth the experiment. For now, though, I will close this issue without implementing.

For future reference, in case we want to reopen it at some point, here is the simple diff:

```
diff --git a/css/master.css b/css/master.css
index b544a8cb..99a60c86 100644
--- a/css/master.css
+++ b/css/master.css
@@ -13,6 +13,11 @@
   src: url(/assets/fonts/ShlomosemiStam.ttf);
 }
 
+@font-face {
+  font-family: 'ShlomoStam';
+  src: url(/assets/fonts/ShlomoStam.ttf);
+}
+
 * {
   box-sizing: border-box;
   margin: 0;
diff --git a/css/page.css b/css/page.css
index 6240d067..65078754 100644
--- a/css/page.css
+++ b/css/page.css
@@ -76,6 +76,10 @@
   width: 100%;
 }
 
+.tikkun-book.mod-annotations-off .tikkun-page {
+  font-family: ShlomoStam;
+}
+
 .tikkun-book.mod-annotations-off .fragment.mod-annotations-on,
 .tikkun-book.mod-annotations-on .fragment.mod-annotations-off {
   display: none;
```
