### ISSUE TITLE
Possible error in text?

### ISSUE THREAD

**Issue by lord-ne** [akivajgordon/tikkun.io#97]
In this tikkun, Bereishit 19:20 has the word spelled "היא", however all other tikkunim and chumashim I've looked at (Artscroll Stone Chumash, Koren Tanakh Maalot, Sefaria, a tikkun korim published by מישור) have "הוא". I'm not sure if this is an error or just a different version, but I can't find anything else that has it written "היא".

tikkun.io:
![2021-10-24 (008)](https://user-images.githubusercontent.com/34069872/138605921-54c5188d-8993-47b7-9ac5-ecadf5bfb17f.jpg)

Sefaria:
![2021-10-24 (007)](https://user-images.githubusercontent.com/34069872/138605928-a3acde09-f702-4e60-a8f4-cccd54e21d0a.png)

**Comment by akivajgordon** [comment]
@lord-ne thanks for raising this! I haven't verified against any other source but I'll take your word for it. Actually the source text used here is from Sefaria, but I pulled it over 5 years ago, so perhaps they had an error at the time and have fixed it by now. I'll repull their source and try to update.

**Comment by akivajgordon** [comment]
@lord-ne So there seems to be an inconsistency with Sefaria's text on their site with [the text that they export](https://github.com/Sefaria/Sefaria-Export/blob/master/json/Tanakh/Torah/Genesis/Hebrew/Tanach%20with%20Ta'amei%20Hamikra.json) (which still shows as "והיא"). So I've manually updated it for now:

![image](https://user-images.githubusercontent.com/6025036/138626001-c8259435-453b-4196-9de9-502d5b2a8aac.png)

Thanks again for reporting.

**Comment by Chajmke** [comment]
It seems you used the text of the Leningrad Manuscript. You'll find this variant in this manuscript (BHS) and you'll have differences in other places as well.

**Comment by akivajgordon** [comment]
@Chajmke Indeed, the text in Sefaria is generated from the Leningrad Codex. Do you know of another source that has the text (with nikkud and ta'amei mikra) in a more accepted variant? And preferably in JSON?

**Comment by lord-ne** [comment]
Sefaria actually appears to have multiple versions of text available. Their main one is מקרא על פי המסורה, and it can be found [here](https://he.m.wikisource.org/wiki/%D7%9E%D7%A9%D7%AA%D7%9E%D7%A9:Dovi/%D7%9E%D7%A7%D7%A8%D7%90_%D7%A2%D7%9C_%D7%A4%D7%99_%D7%94%D7%9E%D7%A1%D7%95%D7%A8%D7%94#%D7%A8%D7%90%D7%A9)

This version of the text has the word spelled הוה, like most chumashim/tikkunim: [Bereishit 19](https://he.m.wikisource.org/wiki/%D7%91%D7%A8%D7%90%D7%A9%D7%99%D7%AA_%D7%99%D7%98/%D7%98%D7%A2%D7%9E%D7%99%D7%9D) (pasuk 20)

I'm not sure if there's any easy way to download the entire text though
